### ISSUE TITLE
store model

### ISSUE THREAD

**Issue by seanjohnite** [scolacur/stackstore#62]
name, description, "URL slug"
stores need a user reference
products need a store reference
our store can be a main store owned by obama

**Comment by seanjohnite** [comment]
Store has a config object containing picture urls, css information, other store-specific styling info

**Comment by dwschrashun** [comment]
each product references a store

add user field to store model
- on product detail check if user owns store
- on order detail filter products by store and give access accordingly

filter products by store

any logged in user can create store

**Comment by seanjohnite** [comment]
frontend: all store-specific states have a /:storeName/ in the front of their url
